---
version: '2.4'

services:
  webpack:
    build: .
    healthcheck:
      test: "node -v"
      retries: 3
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - webpack

  nginx:
    image: nginx:1.21
    healthcheck:
      test: "curl -f 127.0.0.1"
      retries: 3
    volumes:
      - wp_data:/var/www/html
      - ./src/wp-theme:/var/www/html/wp-content/themes/sojourn
      - ./nginx/global:/etc/nginx/global
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - webpack
    ports:
      - 8080:80
    depends_on:
      wordpress:
        condition: service_healthy
      webpack:
        condition: service_healthy

  wordpress:
    image: wordpress:php7.4-fpm
    healthcheck:
      test: "php-fpm --test"
      retries: 3
    volumes:
      - wp_data:/var/www/html
      - ./src/wp-theme:/var/www/html/wp-content/themes/sojourn
      - ./src/wp-plugins/prism:/var/www/html/wp-content/plugins
    networks:
      - frontend
      - backend
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb
    healthcheck:
      test: "/usr/bin/mysql \
            --user=wordpress \
            --password=wordpress \
            --execute \"SHOW DATABASES;\""
      timeout: 2s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    environment:
      MARIADB_ROOT_PASSWORD: wordpress
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress

volumes:
  wp_data: {}
  db_data: {}

networks:
  webpack: {}
  frontend: {}
  backend: {}
