version: '2.4'

services:
  wordpress:
    image: wordpress:php7.4-fpm
    healthcheck:
      test: "php-fpm --test"
      retries: 3
    volumes:
      - wp_data:/var/www/html
      - ./src/wp-theme:/var/www/html/wp-content/themes/sojourn
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      db:
        condition: service_healthy
    
  nginx:
    image: nginx:1.21
    healthcheck:
      test: "curl -f 127.0.0.1"
      retries: 3
    volumes:
      - wp_data:/var/www/html
      - ./src/wp_theme:/var/www/html/wp-content/themes/sojourn
      - ./nginx/global:/etc/nginx/global
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80
    depends_on:
      wordpress:
        condition: service_healthy

  db:
    image: mariadb
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      timeout: 2s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: wordpress
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress

volumes:
  wp_data: {}
  db_data: {}