version: '3.8'

services:
  nginx:
    image: nginx:1.21
    healthcheck:
      test: "curl -f 127.0.0.1"
      retries: 3
    volumes:
      - wp_data:/var/www/html
      - ./wordpress/theme:/var/www/html/wp-content/themes/portfolio
      - ./nginx/global:/etc/nginx/global
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
      - frontend
    depends_on:
      wordpress:
        condition: service_healthy
      webpack:
        condition: service_healthy

  wordpress:
    image: wordpress:php7.4-fpm
    healthcheck:
      test: "php-fpm --test"
      retries: 3
    volumes:
      - wp_data:/var/www/html
      - ./wordpress/theme:/var/www/html/wp-content/themes/portfolio
      - ./wordpress/plugins/prism:/var/www/html/wp-content/plugins
    networks:
      - frontend
      - backend
    environment:
      WORDPRESS_DB_HOST: secret
      WORDPRESS_DB_USER: secret
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: secret
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mariadb
    healthcheck:
      test: "/usr/bin/mysql --user=wordpress --password=wordpress --execute \"SHOW DATABASES;\""
      timeout: 2s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: secret
      MARIADB_USER: secret
      MARIADB_PASSWORD: secret

volumes:
  wp_data: {}
  db_data: {}

networks:
  frontend: {}
  backend: {}