---
version: "2.4"

services:
  nginx:
    image: nginx:1.23
    volumes:
      - wp_data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/wp-content/themes/devontheroof
    networks:
      - frontend
    ports:
      - 80:80
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:php8.2-fpm
    volumes:
      - wp_data:/var/www/html
      - ./:/var/www/html/wp-content/themes/devontheroof
    networks:
      - frontend
      - backend
    env_file:
      - ./.env
    depends_on:
      - db
      - npm

  db:
    image: mariadb:10.7-focal
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    env_file:
      - ./.env

  wp:
    image: wordpress:cli-php8.2
    networks:
      - backend
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ./.env
    entrypoint: ["wp"]
    depends_on:
      - db

  npm:
    image: node:18-bullseye-slim
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    entrypoint: ["npm"]
    command: ["start"]

volumes:
  wp_data: {}
  db_data: {}

networks:
  frontend: {}
  backend: {}
