---
version: '2.4'

services:
  nginx:
    image: nginx:1.21
    volumes:
      - wp_data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/wp-content/themes/devontheroof
    networks:
      - frontend
    ports:
      - 80:80
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    image: wordpress:php7.4-fpm
    volumes:
      - wp_data:/var/www/html
      - ./:/var/www/html/wp-content/themes/devontheroof
    networks:
      - frontend
      - backend
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    healthcheck:
      test: 'php-fpm --test'
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.7-focal
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    environment:
      MARIADB_ROOT_PASSWORD: wordpress
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
    healthcheck:
      test: '/usr/bin/mysql -uwordpress -pwordpress -e "SHOW DATABASES;"'
      timeout: 5s
      interval: 5s
      retries: 5

volumes:
  wp_data: {}
  db_data: {}

networks:
  frontend: {}
  backend: {}
