= D10f
D10f <devontheroof@pm.me>
v1, 2024-06-28
:doctype: article
:source-highlighter: pygments
:icons: font

This is my personal website, where I write notes and guides for my future self about web development, system administration and open source in general.

== Structure

The public folder contains various assets that this site uses to render on the server-side, as well as at runtime. This includes some that are not committed to version control, be it because they're prone to change over time or contain information that is not relevant to the site itself from a technical perspective. This includes things like the `.adoc` files that describe the structure of the site:

pages/ :: all pages except the blog page, which is defined inside the code as a collection of blog posts. Speaking of which...

posts/ :: ...all the individual blog posts are listed here.

uses/ :: the page where I talk about what I use in my own personal setup.

And other files that are loaded as part of some project that I embedded, like the maze screensaver that loads a `.wasm` file.

== What Does "D10f" mean?

It's a https://en.wikipedia.org/wiki/Numeronym[numeronym], an number-based abbreviation for "dev on the roof". I chose this for brevity and because it looked much better than the alternatives: _d13f_, _d16f_ or _d19f_, for the different variations of "dev" and "developer", with and without counting spaces.

== Why "Dev On The Roof"?

Because rooftops tend to have great views, and who doesn't like coding with a great view? Although I actually do all my coding indoors, but don't tell anyone.
