import { getPosts, parsePost } from "@/lib/posts";
import { Title } from "asciidoctor";

// throws a 404 error if the dynamic route was not generated by Next.js
export const dynamicParams = false;

export function generateStaticParams() {
  return getPosts().map((post) => ({
    slug: post.replace(/\..*$/, ""),
  }));
}

export default function Post({ params }: any) {
  const post = parsePost(params.slug);
  const title = post.getDocumentTitle({ partition: true }) as Title;
  return (
    <>
      <header>
        <h1 className="post__title">{title.getMain()}</h1>
        {title.hasSubtitle() && (
          <h2 className="post__subtitle">{title.getSubtitle()}</h2>
        )}
      </header>

      <aside className="post__metadata">
        <span>Published: {post.getRevisionDate()}</span>
        <span>Version: {post.getRevisionNumber()}</span>
      </aside>

      <main
        className="post__content"
        dangerouslySetInnerHTML={{ __html: post.getContent() as string }}
      />
    </>
  );
}
