import type { Metadata } from "next";
import "@/styles/index.scss";

type ChildrenProps = {
  children: Readonly<React.ReactNode>;
};

export const metadata: Metadata = {
  title: "Dev on the roof",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
