import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "@/styles/index.scss";

type ChildrenProps = {
    children: Readonly<React.ReactNode>;
};

export const metadata: Metadata = {
    title: "Dev on the roof",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <div className="separator" />
                {children}
                <Footer />

                <noscript>
                    <style>{`.js-required { display: none }`}</style>
                </noscript>
            </body>
        </html>
    );
}
